certificate.default.cert = "%{file:/opt/stalwart/ssl/cert.pem}%"
certificate.default.default = true
certificate.default.private-key = "%{file:/opt/stalwart/ssl/key.pem}%"
config.local-keys.00 = "store.*"
config.local-keys.01 = "directory.*"
config.local-keys.02 = "tracer.*"
config.local-keys.03 = "!server.blocked-ip.*"
config.local-keys.04 = "!server.allowed-ip.*"
config.local-keys.05 = "server.*"
config.local-keys.06 = "config.local-keys.*"
config.local-keys.07 = "certificate.*"
config.local-keys.08 = "cluster.*"
config.local-keys.09 = "storage.data"
config.local-keys.10 = "storage.blob"
config.local-keys.11 = "storage.lookup"
config.local-keys.12 = "storage.fts"
config.local-keys.13 = "storage.directory"
config.local-keys.14 = "authentication.fallback-admin.*"
config.local-keys.15 = "enterprise.license-key"
config.local-keys.16 = "http.*"
directory.internal.store = "rocksdb"
directory.internal.type = "internal"
server.listener.http.bind = "[::]:8080"
server.listener.http.protocol = "http"
server.listener.imaptls.bind = "[::]:993"
server.listener.imaptls.protocol = "imap"
server.listener.imaptls.tls.implicit = true
server.listener.smtp.bind = "[::]:25"
server.listener.smtp.protocol = "smtp"
server.listener.submissions.bind = "[::]:465"
server.listener.submissions.protocol = "smtp"
server.listener.submissions.tls.implicit = true
server.max-connections = 1024
server.socket.backlog = 256
server.socket.nodelay = true
server.socket.reuse-addr = true
server.socket.reuse-port = true
storage.blob = "rocksdb"
storage.data = "rocksdb"
storage.directory = "internal"
storage.fts = "rocksdb"
storage.lookup = "rocksdb"
store.rocksdb.compression = "lz4"
store.rocksdb.path = "/opt/stalwart/data"
store.rocksdb.type = "rocksdb"
tracer.console.ansi = false
tracer.console.buffered = true
tracer.console.enable = true
tracer.console.level = "info"
tracer.console.lossy = false
tracer.console.multiline = false
tracer.console.type = "stdout"
tracer.log.ansi = false
tracer.log.enable = false
tracer.log.level = "info"
tracer.log.lossy = false
tracer.log.path = "/opt/stalwart/logs"
tracer.log.prefix = "stalwart.log"
tracer.log.rotate = "daily"
tracer.log.type = "log"
